In [20]:
import numpy as np
import pandas as pd
from sklearn import neighbors
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

df = pd.read_csv('data/winequality-red.csv')
#print(df)

In [21]:
def isTasty(quality):
    if quality >= 7:
        return 'Excellent'
    elif quality >= 5:
        return 'Medium'
    else:
        return 'Not good'

In [22]:
df['tasty'] = df['quality'].apply(isTasty)

In [23]:
df.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality', 'tasty'],
      dtype='object')

In [24]:
df['tasty'].value_counts()

Medium       1319
Excellent     217
Not good       63
Name: tasty, dtype: int64

In [32]:
X = np.array(df.drop(['quality', 'tasty'], 1))
y = np.array(df['tasty'])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=5)

clf = neighbors.KNeighborsClassifier()

clf.fit(X_train, y_train)

KNeighborsClassifier()

In [33]:
print('Accuracy', clf.score(X_test, y_test))

Accuracy 0.825


In [34]:
yPredict = clf.predict(X_test)

cm = confusion_matrix(y_test, yPredict, labels=['Excellent','Medium','Not good'])

#tn, fp, fn, tp = cm.ravel()

print(cm)

#print(tn, fp, fn, tp)

#print( (tn + tp) / (tn + tp + fn + fp) )

[[ 11  35   0]
 [ 13 253   1]
 [  0   7   0]]
